(if (>= emacs-major-version 24)
    (progn
      (require 'cl)
      (load-file "~/.emacs.d/general-settings.el")
      (load-file "~/.emacs.d/OS-specific.el")
      (load-file "~/.emacs.d/mypackages.el")
      (load-file "~/.emacs.d/packages-settings.el")
      (load-file "~/.emacs.d/third-part-loading.el"))
  (message "Please Update the emacs"))
(put 'erase-buffer 'disabled nil)
